### ISSUE TITLE
RaspberryPi camera v2 fails to connect to camera with "VIDEOIO ERROR: V$L: can't open camera"

### ISSUE THREAD

**Issue by xginn8** [balena-io-playground/balena-cam#39] opened 2019-07-25 22:21 UTC
A user reported that they were able to fix these issues by upgrading the project to use debian-buster as a base and the following set of packages:

```
RUN apt-get install alsa-utils automake avr-libc bison build-essential flex
RUN apt-get install g++ gcc gcc-avr git gperf htop libtinfo-dev make nano
RUN apt-get install nmap pkg-config psmisc pulseaudio cmake unzip pkg-config
RUN apt-get install -yq gstreamer-1.0 v4l-utils libopus-dev libvpx-dev python3 python3-dev python3-pip python3-setuptools
RUN apt-get install -yq libsrtp2-dev libopencv-dev libatlas3-base libilmbase23 libopenexr23 libavformat-dev libswscale-dev libqtgui4
RUN apt-get install -yq libqt4-test libavdevice-dev libavfilter-dev libavcodec-dev
```

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_r5xf)

**Comment by mbalamat** [comment] 2019-08-02 16:07
Can't reproduce, closing for now.

**Closed by mbalamat** 2019-08-02 16:07 UTC
